version: '3'

networks: 
    laravel:
        driver: bridge

services:

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    hostname: backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/usr/src/backend
    networks:
      - laravel
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '3000:3000'
    networks:
      - laravel
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/frontend
      - '/usr/src/frontend/node_modules'
    
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - '8001:8001'
    volumes:
      - ./backend:/usr/src/backend
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - backend

